import { useQuery } from '@tanstack/react-query'
import { ApiError, apiFetch } from '@/lib/api/client'
import { queryKeys } from '@/lib/query/keys'

/**
 * useReports — the read side of the weekly Report Card (`/reports`). Reports are generated by the
 * generate-reports cron (one weekly_report row per household per week); these hooks only read them
 * back, available to every household member. Mirrors useChores. `reportData` / `aiSuggestions` are
 * jsonb and typed loosely — the cron owns their shape, so consumers narrow as needed.
 */
export type WeeklyReport = {
  id: string
  organizationId: string
  weekStart: string // YYYY-MM-DD (Monday)
  weekEnd: string
  reportData: Record<string, unknown>
  aiSuggestions: unknown[] | null
  mvpMemberId: string | null
  /** Display name of the MVP member, joined server-side (null when no MVP / member removed). */
  mvpMemberName: string | null
  createdAt: string
}

/** Up to the last 12 weeks of report cards, newest first. */
export function useReports(orgId: string) {
  return useQuery({
    queryKey: queryKeys.organizations.reports(orgId),
    queryFn: () => apiFetch<WeeklyReport[]>(`/api/organizations/${orgId}/reports`),
    enabled: Boolean(orgId),
  })
}

/** The most recent week's report card (the screen's headline). Returns null when none exists yet. */
export function useCurrentReport(orgId: string) {
  return useQuery({
    queryKey: [...queryKeys.organizations.reports(orgId), 'current'] as const,
    queryFn: () =>
      apiFetch<WeeklyReport | null>(`/api/organizations/${orgId}/reports/current`).catch((err: unknown) => {
        // No report generated yet (the cron hasn't run for a brand-new household) → 404, not an error.
        if (err instanceof ApiError && err.status === 404) return null
        throw err
      }),
    enabled: Boolean(orgId),
  })
}
