import type { ReactNode } from 'react'
import { ScrollView, View, Pressable, type ImageSourcePropType } from 'react-native'
import { Image } from 'expo-image'
import { router, Link, Stack } from 'expo-router'
import { SafeAreaView } from 'react-native-safe-area-context'
import { Zap, Shield, Sparkles, Rocket } from 'lucide-react-native'
import { cn } from '@/lib/utils'
import { APP_CONFIG } from '@/lib/config/app'
import { MARKETING } from '@/lib/config/marketing'
import { useColors } from '@/lib/config/theme'
import { useIsWideWeb } from '@/lib/hooks/use-is-wide-web'
import { useSession } from '@/lib/auth/client'
import { t } from '@/lib/i18n'
import { Text } from '@/components/ui/text'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Gradient } from '@/components/ui/gradient'

/**
 * Landing — the public marketing page for the WEB build (and a first screen on native).
 *
 * A signed-out web visitor lands here when `APP_CONFIG.authGate.redirectTo === 'landing'` (the
 * default): brand + auth CTAs in a pinned header, a hero, feature cards, and a closing CTA. The app
 * nav is hidden on /landing (NAV_HIDDEN_PREFIXES), so this owns the whole screen. On wide desktop web
 * the hero is two columns; everything stacks on narrow web and native.
 *
 * CUSTOMIZE PER APP at mint time: HERO_TITLE and the FEATURES copy. The imagery — hero, the three
 * feature cards, and the CTA banner — is generated by `builder/assets/generate-marketing.js` (drops
 * each asset + wires the matching MARKETING slot); until a slot is wired it falls back to its branded
 * placeholder (gradient hero / icon cards / gradient banner). Brand mark + name + description come
 * from APP_CONFIG.
 */
const HERO_TITLE = 'Everything you need, in one place.'

const FEATURES = [
  { icon: Zap, title: 'Fast & native', body: 'Built native-first for iOS and Android — and the web.' },
  { icon: Shield, title: 'Private & secure', body: 'Your data, scoped to you and your team.' },
  { icon: Sparkles, title: 'AI built in', body: 'Smart features powered by best-in-class models.' },
]

/**
 * OverlayCard — a marketing photo with a dark bottom scrim and content laid over it. The feature cards
 * and the closing CTA use this when their MARKETING image slot is wired; when it's null they fall back
 * to the icon card / gradient banner. The scrim (transparent → near-black, bottom-weighted) keeps the
 * overlaid white text legible over any photo. `center` vertically centers the content (CTA); otherwise
 * it sits at the bottom (feature cards).
 */
function OverlayCard({
  image,
  wide,
  center,
  children,
}: {
  image: ImageSourcePropType
  wide?: boolean
  center?: boolean
  children: ReactNode
}) {
  return (
    <View className={cn('h-56 overflow-hidden rounded-2xl', wide && 'flex-1')}>
      <Image source={image} style={{ width: '100%', height: '100%' }} contentFit="cover" transition={200} />
      <Gradient
        colors={['rgba(10,8,4,0)', 'rgba(10,8,4,0.82)']}
        direction={[0, 0, 0, 1]}
        borderRadius={0}
        className="absolute inset-0"
      />
      <View
        className={cn(
          'absolute inset-x-0 p-5',
          center ? 'inset-y-0 items-center justify-center gap-4' : 'bottom-0 gap-1',
        )}
      >
        {children}
      </View>
    </View>
  )
}

export default function LandingScreen() {
  const colors = useColors()
  const wide = useIsWideWeb()
  const { data: session } = useSession()
  const initial = (APP_CONFIG.name.trim()[0] ?? 'A').toUpperCase()
  const featureImages = [MARKETING.feature1Image, MARKETING.feature2Image, MARKETING.feature3Image]

  return (
    <View className="flex-1 bg-background">
      <Stack.Screen options={{ headerShown: false }} />

      {/* Marketing header — brand left, auth CTAs right. Pinned above the scroll, always visible. */}
      <SafeAreaView edges={['top']} className="border-b border-border bg-background">
        <View className="w-full max-w-6xl flex-row items-center justify-between gap-4 self-center px-5 py-3">
          {/* min-w-0 + shrink so a long APP_CONFIG.name truncates instead of shoving the CTAs off
              a narrow phone; the auth buttons (shrink-0) always keep their full width. */}
          <View className="min-w-0 shrink flex-row items-center gap-2">
            <View className="size-8 items-center justify-center rounded-lg" style={{ backgroundColor: colors.brand }}>
              <Text variant="label" style={{ color: colors.onPrimary }}>{initial}</Text>
            </View>
            <Text variant="label" numberOfLines={1}>{APP_CONFIG.name}</Text>
          </View>
          <View className="shrink-0 flex-row items-center gap-2">
            {session ? (
              <Button size="sm" label={t('landing.openApp')} onPress={() => router.replace('/')} />
            ) : (
              <>
                <Button variant="ghost" size="sm" label={t('landing.logIn')} onPress={() => router.push('/login')} />
                <Button size="sm" label={t('landing.getStarted')} onPress={() => router.push('/signup')} />
              </>
            )}
          </View>
        </View>
      </SafeAreaView>

      <ScrollView contentContainerClassName="items-center pb-16">
        {/* HERO */}
        <View className="w-full max-w-6xl px-5 pb-10 pt-10">
          <View className={cn('gap-10', wide && 'flex-row items-center')}>
            <View className={cn('gap-5', wide && 'flex-1')}>
              <Text variant="h1" className={cn(wide && 'text-5xl')}>{HERO_TITLE}</Text>
              <Text variant="body" className="max-w-xl text-lg text-muted-foreground">{APP_CONFIG.description}</Text>
              <View className="flex-row flex-wrap gap-3 pt-1">
                <Button label={t('landing.getStarted')} onPress={() => router.push('/signup')} />
                <Button variant="outline" label={t('landing.signIn')} onPress={() => router.push('/login')} />
              </View>
            </View>
            {/* Hero visual — the generated marketing image once wired (MARKETING.heroImage, dropped by
                builder/assets/generate-marketing.js), else a branded gradient placeholder. */}
            <View className={cn(wide ? 'flex-1' : 'w-full')}>
              {MARKETING.heroImage ? (
                <Image
                  source={MARKETING.heroImage}
                  style={{ width: '100%', height: 256, borderRadius: 20 }}
                  contentFit="cover"
                  transition={200}
                  accessibilityLabel={`${APP_CONFIG.name} preview`}
                />
              ) : (
                <Gradient colors={colors.brandGradient} className="h-64 items-center justify-center" borderRadius={20}>
                  <View className="size-24 items-center justify-center rounded-3xl bg-white/15">
                    <Rocket color={colors.onPrimary} size={44} />
                  </View>
                </Gradient>
              )}
            </View>
          </View>
        </View>

        {/* FEATURES — a generated photo per card (title + body overlaid) when wired, else the icon card. */}
        <View className="w-full max-w-6xl px-5 py-6">
          <View className={cn('gap-4', wide && 'flex-row')}>
            {FEATURES.map((f, i) => {
              const img = featureImages[i]
              return img ? (
                <OverlayCard key={f.title} image={img} wide={wide}>
                  <Text variant="label" className="text-white">{f.title}</Text>
                  <Text variant="caption" className="text-white/90">{f.body}</Text>
                </OverlayCard>
              ) : (
                <Card key={f.title} className={cn(wide && 'flex-1')}>
                  <CardContent className="gap-3 p-5">
                    <View className="size-10 items-center justify-center rounded-lg bg-brand-500/10">
                      <f.icon color={colors.brand} size={22} />
                    </View>
                    <Text variant="label">{f.title}</Text>
                    <Text variant="muted">{f.body}</Text>
                  </CardContent>
                </Card>
              )
            })}
          </View>
        </View>

        {/* CLOSING CTA — a generated photo banner (headline + button overlaid) when wired, else the
            brand-gradient banner. The button is an inverse white/brand-label so it never disappears
            against either the gradient (whose first stop IS bg-primary) or a photo. */}
        <View className="w-full max-w-6xl px-5 py-6">
          {MARKETING.ctaImage ? (
            <OverlayCard image={MARKETING.ctaImage} center>
              <Text variant="h2" className="text-center text-white">{t('landing.ctaTitle')}</Text>
              <Button className="bg-white" onPress={() => router.push('/signup')}>
                <Text variant="label" style={{ color: colors.primary }}>{t('landing.getStarted')}</Text>
              </Button>
            </OverlayCard>
          ) : (
            <Gradient colors={colors.brandGradient} className="items-center gap-4 p-8" borderRadius={20}>
              <Text variant="h2" className="text-center" style={{ color: colors.onPrimary }}>
                {t('landing.ctaTitle')}
              </Text>
              <Button className="bg-white" onPress={() => router.push('/signup')}>
                <Text variant="label" style={{ color: colors.primary }}>{t('landing.getStarted')}</Text>
              </Button>
            </Gradient>
          )}
        </View>

        {/* FOOTER */}
        <View className="w-full max-w-6xl flex-row flex-wrap items-center justify-between gap-3 px-5 pt-6">
          <Text variant="caption">© {new Date().getFullYear()} {APP_CONFIG.name}</Text>
          <View className="flex-row gap-5">
            <Link href="/privacy" asChild>
              <Pressable accessibilityRole="link" className="active:opacity-70">
                <Text variant="caption">{t('settings.privacyPolicy')}</Text>
              </Pressable>
            </Link>
            <Link href="/terms" asChild>
              <Pressable accessibilityRole="link" className="active:opacity-70">
                <Text variant="caption">{t('settings.terms')}</Text>
              </Pressable>
            </Link>
          </View>
        </View>
      </ScrollView>
    </View>
  )
}
